
# ROS Gazebo Controller for Duke Bot
controller_manager:
    ros__parameters:
        update_rate: 100

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        omni_wheel_controller:
            type: velocity_controllers/JointGroupVelocityController

omni_wheel_controller:
    ros__parameters:
        joints:
            - wheel1_joint
            - wheel2_joint
            - wheel3_joint
        command_interfaces:
            - position
            - velocity
        state_interfaces:
            - velocity
